### ISSUE TITLE
I can use paraview command but when I use paraFoam it returns "paraview: command not found", why?

### ISSUE THREAD

**Issue by excellenthua** [mrklein/openfoam-os-x#17] opened 2015-11-28 13:00 UTC

**Comment by excellenthua** [comment] 2015-11-28 13:05
I install openfoam 3.0.0 on macbook air, the system version is 10.11.

**Comment by mrklein** [comment] 2015-11-28 16:33
Hi,

I need more information. Could you post output of the following commands (run them in terminal):

1.
```sh
[ -d /Applications/paraview.app ] && echo "OK"
```
2.
```sh
which paraview
```
3.
```sh
type paraview
```

**Comment by excellenthua** [comment] 2015-11-30 02:23
Thank you!

I run the commands and this is the results.

Thank you for you kindness again!

On Sun, Nov 29, 2015 at 1:33 AM, Alexey Matveichev <notifications@github.com

**Comment by mrklein** [comment] 2015-11-30 07:25
And where are the results?

**Comment by excellenthua** [comment] 2015-11-30 07:51
![1130_1](https://cloud.githubusercontent.com/assets/15157443/11466170/6c1ff8ca-9782-11e5-98d2-39eeb5f0e484.jpg)
I am sorry, this morning I replied via email, so the picture is not uploaded correctly.
The results is as the picture shows.
Thank you for you help!

**Comment by mrklein** [comment] 2015-11-30 08:59
Since the problem is zsh-specific feel free to propose solution.

Currently closing the issue with wontfix label.

**Closed by mrklein** 2015-11-30 08:59 UTC
Labels: wontfix
