### ISSUE TITLE
make 2

### ISSUE THREAD

**Issue by hgkrull** [mrklein/openfoam-os-x#38] opened 2017-09-03 11:02 UTC
I got the error during ./Allwmake: 

make[2]: *** No rule to make target `/Users/XYZ/OpenFOAM/OpenFOAM-5.0/platforms/darwin64ClangDPInt32Opt/applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer/JohnsonJacksonSchaefferFrictionalStress.C.dep', needed by `/Users/XYZ/OpenFOAM/OpenFOAM-5.0/platforms/darwin64ClangDPInt32Opt/applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer/JohnsonJacksonSchaefferFrictionalStress.o'.  Stop.
make[1]: *** [reactingEulerFoam] Error 2
make: *** [multiphase] Error 2

Best regards
Hans

**Comment by mrklein** [comment] 2017-09-03 16:13
Hi,

Could you:
1. Attach full log.Allwmake file?
2. Describe the way you have compiled OpenFOAM? This error message in general caused by absence of `applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer/JohnsonJacksonSchaefferFrictionalStress.C` file. I have checked source tree on my laptop, the file is there. Do you have it?

**Comment by hgkrull** [comment] 2017-09-03 16:23
Dear Alexey,




1.) I enclosed the file.
2.) No, the file is missing. I downloaded the latest source.

I will download the tar again and look if the file is there.

Thank you for your help.
Hans

**Comment by mrklein** [comment] 2017-09-05 16:58
Dear Hans,

1. Unfortunately, I do not see log file.
2. I cannot reproduce the error. Neither with 5.0 tar ball, nor with 5.x git clone.

**Comment by hgkrull** [comment] 2017-09-05 18:12
Dear Alexey,

the two files are missing in tay file downloaded from Openfoam. These files are already not there in the 4.0 version but patch worked. I tried the downloaded files with the two missing files replaced from the git. I made a mistake with the log file, I will start again from ground up….

Best regards
Hans

**Comment by hgkrull** [comment] 2017-09-05 19:51
Dear Alexey,

here is the log file.

Best regards
Hans

**Comment by mrklein** [comment] 2017-09-05 20:00
Maybe I am missing something, but here are these files in 4.x tree:

https://github.com/OpenFOAM/OpenFOAM-4.x/tree/master/applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer

Here are these files in 5.x source tree:

https://github.com/OpenFOAM/OpenFOAM-5.x/tree/master/applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer

Since 5.0 is just a tag, here are these files in 5.0 source tree:

https://github.com/OpenFOAM/OpenFOAM-5.x/tree/version-5.0/applications/solvers/multiphase/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJacksonSchaeffer

Log file is still missing. Make a zip of it, maybe Github is not happy about Allwmake extension.

**Comment by hgkrull** [comment] 2017-09-06 04:40
Dear Alexey,


here is the zipped log file. 


Best regards Hans

**Comment by hgkrull** [comment] 2017-09-08 19:01
I tried the 5.x GIT version. Everything runs without problem. so finally I got my 5.x version. Thank you for your support.

Best regards
Hans

**Comment by mrklein** [comment] 2017-09-08 21:46
Thank you for update. May we close the issue?

**Comment by hgkrull** [comment] 2017-09-09 05:58
Please close it.

**Closed** 2017-09-09 08:07 UTC
Labels: 5.0, help wanted
