### ISSUE TITLE
scotch installation fails in Mac 10.14.2 with homebrew

### ISSUE THREAD

**Issue by aqeelahmed168** [mrklein/openfoam-os-x#46] opened 2018-12-16 14:33 UTC
mpicc -O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ -DSCOTCH_PTSCOTCH -I../../include -L../../lib test_scotch_dgraph_redist.c -o test_scotch_dgraph_redist -lptscotch -lscotch -lptscotcherrexit -lm -lz -lpthread -lbz2
make[1]: *** [check] Error 2
make: *** [check] Error 2
make: *** Waiting for unfinished jobs....
./test_strat_par
dyld: __dyld section not supported in /usr/local/Cellar/scotch/6.0.4_1/lib/libptscotch.dylib
make[2]: *** [check_strat_par] Abort trap: 6
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [ptcheck] Error 2
make: *** [ptcheck] Error 2

**Comment by mrklein** [comment] 2018-12-18 21:13
Hi,

Thanks for the report. I do not have access to macOS Mojave, so I won't be able to reproduce the error and fix it. Maybe one day Homebrew will include Scotch in core, right now, you can skip the library installation (it you do not plan to use Scotch decomposition.)

**Comment by aqeelahmed168** [comment] 2018-12-19 16:17
Hi, 
Thanks for the response.
How can I install this library manually, is there any other option?
I have tried a couple of times to install version 5.0 and 4.1 but the compilation stopped at some point. Not same location in both cases. Mixing scotch has to do anything with that ?
I followed the instructions as mentioned for here
https://github.com/mrklein/openfoam-os-x/wiki/OpenFOAM(R)-release-&-Homebrew
Also, the version numbering needs to be updated in your guide. The 5.0 is 5-0 on OpenFOAM server if the new download is required.

**Comment by aqeelahmed168** [comment] 2018-12-19 20:15
I am already using docker. I though direct compilation would create an environment like we get in Linux. Able to directly run through terminal and use multi presserros.

**Comment by mrklein** [comment] 2018-12-19 20:38
@aqeelahmed168 I need more details. Theoretically missing Scotch should not interfere with compilation (as build scripts check library availability and skip corresponding part if library is not installed). Could you post the error message?

Concerning initial error, since in fact it is not a problem of compilation, but a problem of running tests, maybe you can remove tests from scotch formula (comment out everything between `test do` and corresponding `end` in `scotch.rb`).

**Comment by matteoicardi** [comment] 2019-06-11 17:30
same problem here, everything compiles, including scotch with this link [https://raw.githubusercontent.com/jslee02/homebrew-core/3ec5109c8d7bddb6631e9b76f3c540d66f61357f/Formula/scotch.rb],
but then decomposePar and all other parallel utilities give me "section not supported" on the scotch dylib

**Comment by mrklein** [comment] 2019-06-12 18:19
I have pushed 13ee435d5b2006e6e8e8df6692d20be6b7f99d61 to address the issue. Could you test formula file?

**Comment by AleksZhuravljov** [comment] 2019-06-13 15:13
@mrklein ,I had scotch, which was installed as "brew install scotch --without-check". I've made "brew remove scotch" and "brew install scotch.rb" using https://github.com/mrklein/openfoam-os-x/commit/13ee435d5b2006e6e8e8df6692d20be6b7f99d61 and scotch was installed without errors.

**Comment by mrklein** [comment] 2019-06-13 15:25
@AleksZhuravljov, Thank you. Did you have problems with scotch decomposition, described by @matteoicardi ?

**Comment by AleksZhuravljov** [comment] 2019-06-13 15:38
@mrklein I didn't. I guess it can depend on the solver which is used. And I actually don't use parallel utilities. I can test a project where can be such a problem if you pick up one.

**Comment by mrklein** [comment] 2019-06-13 20:31
@AleksZhuravljov: well, if you do not decompose a case, you should not encounter the error. Let's wait for someone, who does decompose their cases.

**Comment by matteoicardi** [comment] 2019-06-18 10:56
Thanks @AleksZhuravljov , it works now!

**Comment by mrklein** [comment] 2019-07-15 13:20
Since, it seems, formula works now, closing the issue.

**Closed by mrklein** 2019-07-15 13:20 UTC
Labels: enhancement
